### ISSUE TITLE
100% Test Coverage

### ISSUE THREAD

**Issue by mferraco** [Shwheelz/capital_one#1]
We need to test everything!

--need to research what testing framework we want to use
--there should also be a code coverage tool we use to make sure we hit everything in the gem

**Comment by mferraco** [comment]
You guys should check out rspec or some other framework for testing the gem.  We definitely should have some unit tests we can run to test that no functionality was broken when we make a change.  Here's some resources you can check out if you want.

http://rspec.info/
http://betterspecs.org/

Here's a list of some other testing frameworks.
https://www.ruby-toolbox.com/categories/testing_frameworks

**Comment by Shwheelz** [comment]
Thanks for the resources.  I was looking at an rspec tutorial earlier today but was having dependency issues with many of the gems on Windows.  I'm going to look into getting a Linux environment setup to bypass these issues

**Comment by mferraco** [comment]
Sounds good man.  Let me know if you run into anymore issues and I can try and help you get it working.

**Comment by Tritonis** [comment]
100% test coverage done courtesy of the C1 folks!
