### ISSUE TITLE
Debug Address Hashes

### ISSUE THREAD

**Issue by mferraco** [Shwheelz/capital_one#19]
Looks like the wrapper is putting address into the system as hashes when its updating a customer.  Need to fix this in the PUT customer method.

**Comment by Tritonis** [comment]
Is this a data format thing? Like it should be input as JSON into the system?

**Comment by mferraco** [comment]
Yeah we were sending a hash as the body of the PUT request to update entities.  It was happening in all the updates (bills, accounts, customers).  I just changed it so that it sends JSON instead and it fixed it.
