### ISSUE TITLE
Failing Tests

### ISSUE THREAD

**Issue by Shwheelz** [Shwheelz/capital_one#22]
*  Transaction
  *  GET
    *  Error on "Specific transaction for an account AND POST for transaction"
      *  JSON::ParseError: 757: unexpected token at '<!DOCTYPE html>...'
  *  DELETE
    *  See error in Transaction GET
*  Withdrawal
  *  DELETE
    *  Failure/Error: expect(withdrawal.class).to be(Net::HTTPNoContent)
    *  got #<Class:70268775297560> => Net::HTTPNotFound
*  Deposit
  *  DELETE
    *  Failure/Error: expect(deposit.class).to be(Net::HTTPNoContent)
    *  got #<Class:70268775297560> => Net::HTTPNotFound

**Comment by Shwheelz** [comment]
Withdrawal and Deposit were utilize an old VCR codebase.  After deleting the /spec/VCR directory, these tests passed

**Comment by Shwheelz** [comment]
Atm GET methods are now returning a hash with "data" and "paging" as the two keys, with all relevant data to the actual methods contained in data => value.  The spec was modified to reflect this change and is now passing

**Comment by mferraco** [comment]
Perfect thanks Shane. Yeah I forgot to mention we implemented paging on
ATMs because there were socmany being returned.

**Comment by Shwheelz** [comment]
Closing this issue because the endpoints changed.  Big update coming soon.
