### ISSUE TITLE
Hashes with pagination not properly accounted for

### ISSUE THREAD

**Issue by Shwheelz** [Shwheelz/capital_one#23]
Need to make an explicit request using Net::HTTP.get_response rather than a method defined by the Ruby wrapper.  Will make calling paginated responses more intuitive in the future.

**Comment by Shwheelz** [comment]
New methods added to account for ATM pagination

**Comment by Tritonis** [comment]
whats goin on in here

**Comment by Shwheelz** [comment]
The devs paginated the JSON for ATMs so I had to write new methods

**Comment by Tritonis** [comment]
So it doesn't do that thing where it gives you a giant wall of text when you query the ATMs anymore?

**Comment by Shwheelz** [comment]
Precisely.  It breaks it up into like 4 giant walls of text :)
