### ISSUE TITLE
API Key Specified by User

### ISSUE THREAD

**Issue by mferraco** [Shwheelz/capital_one#8]
Need to add a way for the user of the gem to specify their API keys and have the gem pick them up.  I need to do some research on how this should be done.

**Comment by mferraco** [comment]
Founds this.  There are a couple different ways of doing it in this article.

http://stackoverflow.com/questions/13673612/creating-a-ruby-gem-requiring-an-api-key-from-user

**Comment by Tritonis** [comment]
I'm kind of leaning towards #2 personally. Just have some sort of method they can call to set it.
