### ISSUE TITLE
ENT/CUST keys for each method

### ISSUE THREAD

**Issue by mferraco** [Shwheelz/capital_one#9]
Need to have a way for the user to specify which key they want to use for each method.  Some methods only accept one of the keys (POST, PUT, DELETE) and other methods don't need either (ATMs, Branches).  Need to so some research on how this should be done.  

Was thinking about adding it as a parameter to the methods that would need it like Account.getAccounts(keyType).  I am trying to find a way to do it without having to add it as an argument for every single method though.

We could possibly have a Cust and Ent object.  So CustAccount.getAccounts, CustAtm.getAtms, etc. would use the user's customer key and EntAccount.getAccounts, EntAtm.getAtms, etc. would use the user's enterprise key.  That could work.  Any ideas on this?

**Comment by Tritonis** [comment]
One other thing for the GET requests, some of them behave differently depending on the type of key you use. For example, Customer.getCustomers with the CUST api key will only return the 3 customers the key is valid for. With the ENT api key it returns all the customers.

We could have a method by which they set their API key. Then they'd be able to set it on the fly, though it might be a little confusing about the differences between the two key's functionality. We'd have to have some disclaimer about the difference between the ENT/CUST keys with the methods though.

**Comment by mferraco** [comment]
After thinking about this a little more, I think the best way would be to expose some Config object that we allow the user to specify what their API Key is.  So before making any calls using the gem they would have to say something like:

```
Config.apiKey = "some key"
```

Then they can change this if they need to change between CUST and ENT key.
